--REGISTRAR CLIENTE
--======================================================
CREATE PROCEDURE P0001  
@IDC INT,
@NOMB VARCHAR(30),
@APE VARCHAR(30),
@DNI VARCHAR(7)
AS
BEGIN
INSERT INTO CLIENTE VALUES(@IDC, @NOMB,@APE,@DNI)
END

--ACTUALIZAR CLIENTE
--======================================================
CREATE PROCEDURE P0002
@IDC INT,
@NOMB VARCHAR(30),
@APE VARCHAR(30),
@DNI VARCHAR(7)
AS
BEGIN
UPDATE CLIENTE
SET Nomb=@NOMB, Ape=@APE, DNI=@DNI
WHERE IDC=@IDC 
END

--ELIMINAR CLIENTE
--======================================================
CREATE PROCEDURE P0003
@IDC INT
AS 
BEGIN
DELETE 
FROM CLIENTE 
WHERE IDC =@IDC
END

--REGISTRAR EN GARAJE
--======================================================
CREATE PROCEDURE P0004
@SLOT INT,
@PLACA VARCHAR(7),
@DNI VARCHAR(7)
AS
BEGIN
UPDATE GARAJE
SET PLACA=@PLACA, DNI=@DNI, DISPO=1
WHERE SLOT=@SLOT
END

--LIBERAR EN GARAJE
--======================================================
CREATE PROCEDURE P0005
@SLOT INT,
@PLACA VARCHAR(7),
@DNI VARCHAR(7)
AS
BEGIN
UPDATE GARAJE
SET PLACA='', DNI='', DISPO=0
WHERE SLOT=@SLOT
END

--ASIGNAR HABITACIÓN
--======================================================
CREATE PROCEDURE P0006
@IDH INT,
@IDC INT
AS
BEGIN
UPDATE HABITACION
SET ESTADO=1, IDC=@IDC
WHERE IDH = @IDH
END

--DESASIGNAR HABITACIÓN
--======================================================
CREATE PROCEDURE P0007
@IDH INT
AS 
BEGIN
UPDATE HABITACION
SET ESTADO=2, IDC=10001
WHERE IDH=@IDH
END

--HABILITAR HABITACIÓN
--======================================================
CREATE PROCEDURE P0008
@IDH INT
AS
BEGIN
UPDATE HABITACION
SET ESTADO=0
WHERE IDH = @IDH
END

--PAGO CLIENTE
--======================================================
CREATE PROCEDURE PC001
@ID INT,
@IDC INT,
@FECHA VARCHAR(8),
@MONTO VARCHAR(7),
@IGV VARCHAR(7)
AS
BEGIN
INSERT INTO BOLETA VALUES(@ID,@IDC,@FECHA,@MONTO,@IGV)
END