--REGISTRAR CLIENTE
--======================================================
CREATE PROCEDURE P0001  
@NOMB VARCHAR(30),
@APE VARCHAR(30),
@DNI VARCHAR(7)
AS
BEGIN
INSERT INTO CLIENTE VALUES(@NOMB,@APE,@DNI)
END

--ACTUALIZAR CLIENTE
--======================================================
CREATE PROCEDURE P0002
@NOMB VARCHAR(30),
@APE VARCHAR(30),
@DNI VARCHAR(7)
AS
BEGIN
UPDATE CLIENTE
SET Nomb=@NOMB, Ape=@APE, DNI=@DNI
WHERE IDC= @DNI
END

--ELIMINAR CLIENTE
--======================================================
CREATE PROCEDURE P0003
@DNI INT
AS 
BEGIN
DELETE 
FROM CLIENTE 
WHERE DNI =@DNI
END

--REGISTRAR EN GARAJE
--======================================================
CREATE PROCEDURE P0004
@SLOT INT,
@PLACA VARCHAR(7),
@DNI VARCHAR(7)
AS
BEGIN
UPDATE GARAJE
SET PLACA=@PLACA, DNI=@DNI, DISPO=1
WHERE SLOT=@SLOT
END

--LIBERAR EN GARAJE
--======================================================
CREATE PROCEDURE P0005
@SLOT INT
AS
BEGIN
UPDATE GARAJE
SET PLACA='', DNI='', DISPO=0
WHERE SLOT=@SLOT
END

--ASIGNAR HABITACIÓN
--======================================================
CREATE PROCEDURE P0006
@IDH INT,
@IDC INT
AS
BEGIN
UPDATE HABITACION
SET ESTADO=1, IDC=@IDC
WHERE IDH = @IDH
END

--DESASIGNAR HABITACIÓN
--======================================================
CREATE PROCEDURE P0007
@IDH INT
AS 
BEGIN
UPDATE HABITACION
SET ESTADO=2, IDC=10001
WHERE IDH=@IDH
END

--HABILITAR HABITACIÓN
--======================================================
CREATE PROCEDURE P0008
@IDH INT
AS
BEGIN
UPDATE HABITACION
SET ESTADO=0
WHERE IDH = @IDH
END

--PAGO CLIENTE
--======================================================
CREATE PROCEDURE PC001
@DNI INT,
@FECHA VARCHAR(8),
@MONTO VARCHAR(7),
@IGV VARCHAR(7)
AS
BEGIN
INSERT INTO BOLETA VALUES(@DNI,@FECHA,@MONTO,@IGV)
END

--LISTAR CLIENTES
--======================================================
CREATE PROCEDURE P0009
AS
BEGIN
SELECT Nomb AS 'Nombre', Ape AS 'Apellido', DNI 
	FROM CLIENTE
END
--LISTAR HABITACIONES
--======================================================
CREATE PROCEDURE P0010
AS
BEGIN 
SELECT num AS 'Cuarto', Nomb AS 'Nombres', Ape AS 'Apellidos',DNI, DESCRIPCION AS 'Descripción'
	FROM HABITACION
	INNER JOIN CLIENTE ON (HABITACION.IDC=CLIENTE.IDC)
	INNER JOIN ESTADOH ON (HABITACION.ESTADO = ESTADOH.ESTADO)
END

--LISTAR GARAJE 
--======================================================
CREATE PROCEDURE P0011
AS 
BEGIN 
	SELECT SLOT AS 'Número', PLACA AS 'Placa', DNI, DESCRIPCION AS 'Descripción'
	FROM GARAJE
	INNER JOIN ESTADOG ON (GARAJE.DISPO = ESTADOG.DISPO)
END

--LISTAR INVENTARIO 
--======================================================
CREATE PROCEDURE P0012
AS
BEGIN
SELECT IDI AS 'ID', TIPO, NUM AS 'CUARTO', DESCRIPCION AS 'DESCIPCIÓN'
	FROM INVENTARIO
	INNER JOIN HABITACION ON (INVENTARIO.IDH = HABITACION.IDH)
	INNER JOIN ESTADOI ON (INVENTARIO.ESTADO = ESTADOI.ESTADO)
END

--Last ID CLIENTE
--======================================================
CREATE PROCEDURE P0013
AS
BEGIN
SELECT	top 1 IDC
FROM CLIENTE
END